# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cJ5krUmldixm61fFAX5pO6iCSq_5LP8D
"""


import streamlit as st
import pickle
import numpy as np
import os

# Load the saved scaler and KMeans model
scaler_path = os.path.join(os.path.dirname(__file__), 'scaler.pkl')
model_path = os.path.join(os.path.dirname(__file__), 'kmeans_model.pkl')

with open(scaler_path, 'rb') as f:
    scaler = pickle.load(f)

with open(model_path, 'rb') as f:
    kmeans = pickle.load(f)


# Custom cluster labels (adjust if needed)
cluster_labels = {
    0: 'Loyal High Spend Customers',
    1: 'Inactive or Low Spend Customers',
    2: 'VIP High Frequency & High Spend',
    3: 'Moderately Engaged Customers'
}

# Streamlit UI
st.title("🧠 Customer Segment Predictor")
st.write("Enter the RFM values to predict the customer's segment:")

# Input fields
recency = st.number_input("Recency (days since last purchase)", min_value=0)
frequency = st.number_input("Frequency (number of purchases)", min_value=0)
monetary = st.number_input("Monetary (total spent in currency)", min_value=0.0)

# Prediction
if st.button("Predict Segment"):
    input_data = np.array([[recency, frequency, monetary]])
    scaled_data = scaler.transform(input_data)
    cluster = kmeans.predict(scaled_data)[0]
    label = cluster_labels.get(cluster, "Unknown Segment")

    st.success(f"🧾 This customer belongs to: **{label}** (Cluster {cluster})")

# Footer
st.markdown("---")
st.markdown("Made with ❤️ by [Bhavya Mistry](https://github.com/Bhavya-Mistry)")